# on: 
#     workflow_dispatch:
#       inputs:
#         environment:
#           description: 'Have you stored the PAT token?'
#           default: 'stored'
#           required: true
#       branches:
#         - 'main'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Have you stored your MY_PAT Token?'
        required: true
        default: 'Stored'
  # push:
    branches:
      - 'main'

name: branch-setup
env:
  STORAGE_UI_AUTH: ${{ secrets.STORAGE_UI_AUTH }}  
  MY_PAT: ${{ secrets.MY_PAT }}

jobs: 
    setup:
      runs-on: ubuntu-latest
      steps: 
        - run: echo "First workflow triggered"
        
    printInputs: 
      steps:
        - run: |
            echo "Env: ${{ github.event.input.environment }}"
  