name: action_to_validate_the_env_variable
on: workflow_dispatch
jobs:
  env_test:
    env:
      cloud: azure
      authentication: spn
      cloud_env: aws
    steps:
      - name: print the env name
        if: ${{ env.authentication == 'spn'}}
        run: |
            echo "The cloud is ${{ env.cloud }}"
        




