name: action_to_validate_the_env_variable

on: 
  workflow_dispatch

jobs:
  env_test:
    runs-on: ubuntu-latest
    env:
      cloud: azure
    steps:
      - name: test1
        run: |
          echo "${{ env.cloud }}"

 
        




